# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Build

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/TJ/portfolio
          git pull portfolio develop
          rm -rf /var/www/tjbrackett.com/*
          npm i
          npm run build
          mv ~/TJ/portfolio/build/* /var/www/tjbrackett.com/
          cd
          exit
